language: ruby
rvm:
 - 2.4
addons:
  postgresql: "9.4"
  code_climate:
    repo_token: 906e626c483f789c8e7ee3ef77acacc20788edbe8f0dc35cf759f3eecd9f6a09
before_script:
  - psql -c 'create database magmonitor_test;' -U postgres
  - cp config/database.yml.travis config/database.yml
  - bundle exec rake db:schema:load
install:
  - bundle install
  - rm -rf ~/.nvm && git clone https://github.com/creationix/nvm.git ~/.nvm && (cd ~/.nvm && git checkout `git describe --abbrev=0 --tags`) && source ~/.nvm/nvm.sh
  - command -v nvm
  - nvm install lts/boron
  - node -v
  - npm i -g yarn
  - yarn
cache:
  bundler: true
  directories:
    - $HOME/.yarn-cache
  yarn: true
after_success:
  - bundle exec codeclimate-test-reporter
